"""Tests for value providers (the swappable value-generation strategies)."""

import random

import pytest

from gen3_metadata_simulator.providers.base import ValueProvider, ValueRequest
from gen3_metadata_simulator.providers.llm_provider import LLMValueProvider
from gen3_metadata_simulator.providers.random_provider import RandomValueProvider


def test_enum_request_returns_allowed_value():
    """An enum request always yields one of the declared options.

    Categorical fields are generated by sampling the schema's enum, so the
    output is guaranteed in-domain without any external knowledge.
    """
    provider = RandomValueProvider(random.Random(0))
    req = ValueRequest(node="n", name="p", json_type="string", enum=["a", "b", "c"])
    assert provider.value(req) in {"a", "b", "c"}


def test_integer_respects_bounds():
    """Integer generation honours minimum/maximum from the schema.

    Numeric constraints in the schema must be respected or the value would fail
    validation; here a tight [10, 12] range must always be satisfied.
    """
    provider = RandomValueProvider(random.Random(0))
    req = ValueRequest(node="n", name="p", json_type="integer", minimum=10, maximum=12)
    for _ in range(50):
        v = provider.value(req)
        assert isinstance(v, int) and 10 <= v <= 12


def test_pattern_string_matches_regex():
    """A string property with a 'pattern' yields a value matching that regex.

    Many Gen3 fields (dates, ontology codes) are plain strings constrained only
    by a regex pattern; the provider must satisfy the pattern exactly.
    """
    import re

    provider = RandomValueProvider(random.Random(1))
    pattern = r"^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
    req = ValueRequest(node="n", name="d", json_type="string", pattern=pattern)
    assert re.match(pattern, provider.value(req))


def test_random_provider_is_deterministic_under_seed():
    """Identical seeds give identical value sequences (run reproducibility)."""
    req = ValueRequest(node="n", name="p", json_type="number", minimum=0, maximum=1)
    a = [RandomValueProvider(random.Random(5)).value(req) for _ in range(1)]
    b = [RandomValueProvider(random.Random(5)).value(req) for _ in range(1)]
    assert a == b


def test_value_provider_abc_cannot_be_instantiated():
    """The abstract base cannot be used directly — a concrete strategy is required."""
    with pytest.raises(TypeError):
        ValueProvider()  # type: ignore[abstract]


def test_llm_provider_not_implemented_in_v1():
    """The LLM provider exists as a stub and raises until v2 lands.

    The interface is defined now so the generator can target it unchanged, but
    calling it must fail loudly rather than silently producing bad data.
    """
    provider = LLMValueProvider(random.Random(0))
    req = ValueRequest(node="n", name="p", json_type="number")
    with pytest.raises(NotImplementedError):
        provider.value(req)
