# Build and test on pushes and pull requests.
name: Build and Test

on:
  push:
    branches:
      - main
      - 'feat/**'
      - 'fix/**'
      - 'refactor/**'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Build package
        run: poetry build

      - name: Run tests
        run: poetry run python -m pytest
